# frozen_string_literal: true

source "https://rubygems.org"

gem "rails", "~> 6.1"
gem "pg", "~> 1.0"

gem "dotenv"
gem "faker"

gem 'roaring_fkey', path: '../'#, branch: :master

gem "memory_profiler"
gem "benchmark-ips"
gem "rainbow"

gem 'mutex_m'
gem 'base64'
gem 'bigdecimal'
gem 'tracer'
gem 'drb'
gem 'csv'
gem 'rubyzip'
gem 'concurrent-ruby', '~> 1.2'

group :development, :test do
  gem 'rspec', '~> 3.12'
end